---
apiVersion: v1
kind: Pod
metadata:
  name: app22
  labels:
    app: app22
  annotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/role: 'app22'
    vault.hashicorp.com/tls-skip-verify : 'true'
    vault.hashicorp.com/agent-inject-secret-config.txt: 'kvsecret/data/app22'
    vault.hashicorp.com/secret-volume-path: /secrets
spec:
  containers:
  - image: teymurgahramanov/app22
    name: app22
  serviceAccountName: app22