---
apiVersion: v1
kind: Pod
metadata:
  name: app22
  labels:
    app: app22
  annotations:
    vault.security.banzaicloud.io/vault-addr: "https://vault.vault:8200"
    vault.security.banzaicloud.io/vault-role: "app22"
    vault.security.banzaicloud.io/vault-skip-verify: "true"
    vault.security.banzaicloud.io/readonly-root-fs: "true"
    vault.security.banzaicloud.io/vault-ignore-missing-secrets: "true"
spec:
  containers:
  - image: teymurgahramanov/app22
    name: app22
    env:
      - name: DB_PASSWORD
        value: "vault:kvsecret/data/app22#DB_PASSWORD"
  serviceAccountName: app22